apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: three-tier
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: priya720/backend:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGO_HOST
            value: "docdb-2025-10-18-10-13-30.cluster-clg2gusui41h.ap-south-1.docdb.amazonaws.com:27017/admin?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&authMechanism=SCRAM-SHA-1"
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: docdb-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: docdb-sec
                key: password
          - name: USE_DB_AUTH
            value: "true"
        ports:
          - containerPort: 3500
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
          - name: docdb-ca
            mountPath: /etc/ssl/certs
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3500
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 3500
          initialDelaySeconds: 60   # give DB connection time
          periodSeconds: 5
          failureThreshold: 12
        startupProbe:
          httpGet:
            path: /started
            port: 3500
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 60
      volumes:
        - name: docdb-ca
          configMap:
            name: docdb-ca-config
