apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: three-tier
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      initContainers:
      - name: wait-for-mongo
        image: busybox:1.35
        command:
          - sh
          - -c
          - |
            echo "Waiting for mongodb-svc:27017..."
            until nc -z mongodb-svc 27017; do
              echo "mongo not reachable yet; sleeping 2s"
              sleep 2
            done
            echo "mongodb is reachable"
      containers:
      - name: api
        image: priya720/backend
        imagePullPolicy: IfNotPresent
        env:
          - name: MONGO_CONN_STR
            value: mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-svc:27017/admin
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
          - name: USE_DB_AUTH
            value: "true"
        ports:
        - containerPort: 3500
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 3500
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /started
            port: 3500
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 60
